#######################################################################################################################
# 
#
# Source: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
#######################################################################################################################
---
- set_fact:
    apiserver: '--apiserver-advertise-address {{ master_ip }}'
  when: master_ip is defined

- name: Initialize the cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 {{ apiserver | default("") }} >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: create .kube directory
  become: yes
  become_user: kube
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/kube/.kube/config
    remote_src: yes
    owner: kube

- name: install Pod network
  become: yes
  become_user: kube
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt